/* the vendored browser package — in-page observer + guarded execution support.
 *
 * Installed on the TOP-LEVEL window only (same-origin frames reach it through
 * window.top). Responsibilities:
 *
 *   1. readState()   — one atomic read of visible text + actionable elements,
 *                      each with a code-owned, observation-stable ref.
 *   2. verify()      — strict freshness: still the page and element observed?
 *   3. reinspect()   — relaxed freshness: still the same control? Used for the
 *                      second and later ops of a batch, where earlier ops have
 *                      legitimately mutated the page.
 *   4. resolve()     — geometry + occlusion, recomputed just before input.
 *
 * Design rules (carried over from browser-use/jev-ultrafast):
 *   - Refs are owned by code, never generated by a model.
 *   - Geometry is always re-resolved immediately before input.
 *   - Page text is untrusted data, never instructions.
 */
(() => {
  const W = window;
  try { if (W !== W.top) return; } catch (_) { return; }
  if (W.__jevMcp && W.__jevMcp.version === 15) return;

  // Refs survive a helper re-injection, so an agent can keep referring to e37
  // across observes. `next` is monotonic: a pruned ref is never recycled.
  const S = W.__jevRefs || (W.__jevRefs = { ids: new WeakMap(), nodes: new Map(), next: 1, snap: null });

  const ROLES = ['button', 'link', 'checkbox', 'radio', 'switch', 'tab', 'menuitem',
    'menuitemcheckbox', 'menuitemradio', 'option', 'treeitem', 'gridcell', 'combobox',
    'textbox', 'searchbox', 'spinbutton', 'listbox'];
  const SELECTOR = 'a[href],button,input,textarea,select,summary,[contenteditable=""],' +
    '[contenteditable="true"],' + ROLES.map(r => '[role="' + r + '"]').join(',');
  const UNSAFE_TYPES = ['hidden'];

  // aa/P2: cookie-consent containers (guard.py's exemption keys off `consent`). Kept in sync with
  // guard.CONSENT_CONTAINERS. A control inside one of these is a cookie control, not an application control.
  const CONSENT_SELECTOR = '#onetrust-banner-sdk,#onetrust-consent-sdk,#CybotCookiebotDialog,' +
    '#didomi-host,#usercentrics-root,#truste-consent-track,.qc-cmp2-container';

  // Word-bounded on purpose: /pass/ alone flags "Passengers", /code/ alone
  // flags every "Promo code" field.
  const SECRET_HINT = new RegExp([
    'password', 'passwd', 'passcode', 'passphrase', 'otp', 'one[- ]?time',
    'verification code', 'security code', 'cvv', 'cvc', 'card\\s*number',
    'secret', 'api\\s*key', 'access\\s*token', 'ssn', 'social security',
    'iban', 'routing\\s*number', 'security\\s*answer', '\\bpin\\b',
  ].join('|'), 'i');

  const PRIMARY = new Set(['button', 'combobox', 'listbox', 'textbox', 'searchbox',
    'checkbox', 'radio', 'switch', 'spinbutton', 'file', 'listbox']);
  const SECONDARY = new Set(['option', 'tab', 'menuitem', 'menuitemcheckbox',
    'menuitemradio', 'treeitem', 'gridcell', 'radio', 'checkbox', 'switch']);

  /* ---------------------------------------------------------------- helpers */

  const clean = s => (s || '').replace(/\s+/g, ' ').trim();

  const identity = e => {
    if (!S.ids.has(e)) { S.ids.set(e, S.next++); S.nodes.set(S.ids.get(e), e); }
    return S.ids.get(e);
  };

  const prune = () => { for (const [id, e] of S.nodes) if (!e.isConnected) S.nodes.delete(id); };

  const typeOf = e => ((e.getAttribute && e.getAttribute('type')) || '').toLowerCase();
  const isFile = e => e.tagName === 'INPUT' && typeOf(e) === 'file';

  // aa2: while a modal <dialog> is open (showModal), everything outside it is inert (HTML: "blocked by a modal
  // dialog"): it cannot be clicked or typed into, so it is not listed and its text is not read. Cached ~50 ms.
  const openModal = () => {
    const t = performance.now();
    if (!(t - (S.modalAt || -1e9) < 50)) {
      // aa4: with several modal dialogs open (LinkedIn's "Save this application?" prompt over Easy Apply,
      // live 2026-09-23) only the topmost is interactive: the last one, in DOM order, hit at its own centre.
      S.modal = null;
      try {
        const modals = [...document.querySelectorAll('dialog:modal')];
        for (let i = modals.length - 1; i >= 0 && !S.modal; i--) {
          const r = modals[i].getBoundingClientRect();
          const hit = document.elementFromPoint(r.left + r.width / 2, r.top + r.height / 2);
          if (hit && insideNode(hit, modals[i])) S.modal = modals[i];
        }
        if (!S.modal && modals.length) S.modal = modals[modals.length - 1];
      } catch (_) { S.modal = null; }
      S.modalAt = t;
    }
    return S.modal;
  };
  const insideNode = (e, m) => {
    let n = e, guard = 0;
    while (n && guard++ < 10000) {
      if (n === m) return true;
      if (n.parentNode) { n = n.parentNode; continue; }
      if (n.host) { n = n.host; continue; }                      // shadow root → its host
      const view = n.defaultView;                                 // a frame's document → its <iframe>
      n = view && view.frameElement ? view.frameElement : null;
    }
    return false;
  };

  const deepVisible = e => {
    const modal = openModal();
    if (modal && e && !insideNode(e, modal)) return false;
    let n = e;
    while (n && n.nodeType === 1) {
      if (n.closest && n.closest('[aria-hidden="true"],[inert]')) return false;
      // aa1: a `display: contents` wrapper generates no box, so checkVisibility() is false for it, yet it hides
      // nothing: its children render normally. Skip the box test for it (aria-hidden / inert above still apply).
      // aa3: a native radio / checkbox / file input with opacity 0 is the usual custom-control pattern (the input
      // stays in place and clickable under a styled label; Ashby, live 2026-09-23). Its own opacity is ignored;
      // its ancestors' opacity still counts.
      const ownControl = n === e && n.tagName === 'INPUT' && /^(radio|checkbox|file)$/i.test(n.type || '');
      try {
        if (!n.checkVisibility({ checkOpacity: !ownControl, checkVisibilityCSS: true })
            && getComputedStyle(n).display !== 'contents') return false;
      } catch (_) { return false; }
      if (n.parentElement) { n = n.parentElement; continue; }
      const root = n.getRootNode && n.getRootNode();
      n = root && root instanceof ShadowRoot ? root.host : null;
    }
    return true;
  };

  // `document.elementFromPoint` stops at a shadow host, so a control inside a
  // web component looks permanently "covered". Descend the shadow tree.
  const deepElementFromPoint = (doc, x, y) => {
    let element = doc.elementFromPoint(x, y);
    let guard = 0;
    while (element && element.shadowRoot && guard++ < 12) {
      const inner = element.shadowRoot.elementFromPoint(x, y);
      if (!inner || inner === element) break;
      element = inner;
    }
    return element;
  };

  const roleOf = e => {
    const explicit = e.getAttribute('role');
    if (explicit && ROLES.includes(explicit)) return explicit;
    const tag = e.tagName;
    if (tag === 'BUTTON' || tag === 'SUMMARY') return 'button';
    if (tag === 'A') return 'link';
    if (tag === 'SELECT') return e.multiple ? 'listbox' : 'combobox';
    if (tag === 'TEXTAREA' || e.isContentEditable) return 'textbox';
    if (tag === 'INPUT') {
      const t = typeOf(e);
      if (t === 'checkbox') return 'checkbox';
      if (t === 'radio') return 'radio';
      if (['button', 'submit', 'reset', 'image'].includes(t)) return 'button';
      if (t === 'search') return 'searchbox';
      if (t === 'number') return 'spinbutton';
      if (t === 'file') return 'file';
      if (['text', 'email', 'url', 'tel', 'date', 'datetime-local', 'month',
        'week', 'time', 'password'].includes(t)) return 'textbox';
    }
    return null;
  };

  const FLAT = ['button', 'submit', 'reset', 'image'];

  const nameOf = (e, seen) => {
    seen = seen || new Set();
    if (!e || seen.has(e)) return '';
    seen.add(e);
    const byId = (e.getAttribute('aria-labelledby') || '').split(/\s+/)
      .map(id => nameOf(document.getElementById(id), seen)).filter(Boolean).join(' ');
    if (byId) return byId;
    const label = e.getAttribute('aria-label');
    if (label) return label;
    if (e.labels && e.labels.length) {
      const fromLabel = [...e.labels].map(l => nameOf(l, seen)).filter(Boolean).join(' ');
      if (fromLabel) return fromLabel;
    }
    if (FLAT.includes(typeOf(e)) && e.value) return e.value;
    if (e.getAttribute('alt')) return e.getAttribute('alt');
    if (e.tagName !== 'INPUT' && e.tagName !== 'TEXTAREA') {
      // Skip Greenhouse's `.ada-unique-content` span: an sr-only, non-aria-hidden per-render random token
      // (e.g. "e56527e9") inside the field's <label>. Folding it into the name made every Greenhouse field
      // label change across a re-render/reload, so read-back could never match the filled field and the whole
      // form failed as broken_form (live 2026-10-07, Toast). It is not part of the question.
      const fromText = [...e.childNodes].map(n => n.nodeType === 3 ? n.textContent
        : n.nodeType === 1 && n.getAttribute('aria-hidden') !== 'true'
          && !(n.classList && n.classList.contains('ada-unique-content')) ? nameOf(n, seen) : '').join(' ').trim();
      if (fromText) return fromText;
    }
    return e.getAttribute('title') || e.getAttribute('placeholder') || '';
  };

  const valueOf = e => {
    if (isFile(e)) return e.files && e.files.length ? [...e.files].map(f => f.name).join(', ') : '';
    if ('value' in e && !['checkbox', 'radio'].includes(typeOf(e))) return String(e.value == null ? '' : e.value);
    if (e.isContentEditable) return clean(e.innerText);
    if (roleOf(e) === 'combobox' && e.tagName !== 'SELECT') return clean(e.innerText);
    return '';
  };

  const disabled = e => e.matches(':disabled') || !!e.closest('[aria-disabled="true"],[inert]');

  const isEditable = e => {
    if (isFile(e) || e.tagName === 'SELECT') return false;
    const role = roleOf(e);
    if (!['textbox', 'searchbox', 'spinbutton', 'combobox'].includes(role)) return false;
    if (role === 'combobox' && !['INPUT', 'TEXTAREA'].includes(e.tagName)) return false;
    if (e.readOnly || e.getAttribute('aria-readonly') === 'true') return false;
    if (disabled(e)) return false;
    return true;
  };

  /* ------------------------------------------------------- frame traversal */

  const frameChainOf = e => {
    const chain = [];
    let view = e.ownerDocument && e.ownerDocument.defaultView;
    let guard = 0;
    while (view && view !== W && guard++ < 12) {
      let fe = null;
      try { fe = view.frameElement; } catch (_) { fe = null; }
      if (!fe) break;
      chain.unshift(fe);
      try { view = fe.ownerDocument.defaultView; } catch (_) { break; }
    }
    return chain;
  };

  // Cheap offset: geometry only, no hit test. Used for ranking.
  const frameOffset = chain => {
    let x = 0, y = 0;
    for (const f of chain) {
      if (!f.isConnected || !deepVisible(f)) return null;
      const r = f.getBoundingClientRect();
      x += r.x; y += r.y;
    }
    return { x, y };
  };

  // Strict offset: also proves every frame in the chain is actually hit-testable.
  const offsetFor = chain => {
    let x = 0, y = 0;
    for (const f of chain) {
      if (!f.isConnected || !deepVisible(f)) return { ok: false, reason: 'frame_hidden' };
      const r = f.getBoundingClientRect();
      const doc = f.ownerDocument, view = doc.defaultView;
      const hx = r.x + r.width / 2, hy = r.y + r.height / 2;
      if (hx < 0 || hy < 0 || hx >= view.innerWidth || hy >= view.innerHeight) {
        return { ok: false, reason: 'frame_out_of_viewport' };
      }
      const hit = deepElementFromPoint(doc, hx, hy);
      if (!hit || !(hit === f || f.contains(hit))) return { ok: false, reason: 'frame_occluded' };
      x += r.x; y += r.y;
    }
    return { ok: true, x, y };
  };

  const rootList = () => {
    const out = [];
    const cross = [];
    const visit = (doc, chain, depth) => {
      if (depth > 6) return;
      out.push({ doc, chain });
      let frames = [];
      try { frames = doc.querySelectorAll('iframe,frame'); } catch (_) { return; }
      for (const f of frames) {
        let cd = null;
        try { cd = f.contentDocument; } catch (_) { cd = null; }
        if (cd && cd.body) visit(cd, chain.concat([f]), depth + 1);
        else cross.push({ chain: chain.concat([f]), src: f.getAttribute('src') || '' });
      }
    };
    visit(document, [], 0);
    return { roots: out, cross };
  };

  const rootsOf = root => {
    const out = [root];
    let all = [];
    try { all = root.querySelectorAll('*'); } catch (_) { return out; }
    if (all.length > 20000) return out;
    for (const e of all) if (e.shadowRoot) out.push(...rootsOf(e.shadowRoot));
    return out;
  };

  /* ------------------------------------------------------------ page state */

  const pageFields = () => [...document.querySelectorAll('input,textarea,select')]
    .filter(e => !UNSAFE_TYPES.includes(typeOf(e)))
    .map(e => [identity(e), valueOf(e), !!e.checked, e.selectedIndex, e.disabled, e.readOnly]);

  // Scroll is deliberately excluded: geometry is re-resolved before every
  // input anyway, so a scroll (ours or the page's) is not a semantic change
  // and must not invalidate a decision. Form values are included, because
  // those genuinely change what a ref means.
  const keyOf = () => JSON.stringify([performance.timeOrigin, location.href,
    innerWidth, innerHeight, pageFields()]);

  const scopeOf = e => e.closest('form,dialog,[role="dialog"],article,li,tr,[role="row"],[role="listitem"]') || e.parentElement;

  const guardOf = e => {
    if (!e || !e.isConnected || !deepVisible(e)) return null;
    const scope = scopeOf(e);
    return JSON.stringify([identity(e), roleOf(e), nameOf(e), valueOf(e),
      typeOf(e) && ['checkbox', 'radio'].includes(typeOf(e)) ? !!e.checked : null,
      e.selectedIndex == null ? null : e.selectedIndex, !!e.readOnly, disabled(e),
      e.getAttribute('aria-disabled'), e.getAttribute('aria-expanded'),
      e.getAttribute('aria-checked'), e.getAttribute('aria-selected'), e.getAttribute('href'),
      scope ? clean(scope.innerText).slice(0, 400) : '']);
  };

  const textOf = max => {
    const words = [];
    if (!document.body) return '';   // a just-navigated / loading tab has no body yet: createTreeWalker(null) throws
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const range = document.createRange();
    let node, length = 0;
    while ((node = walker.nextNode()) && length < max) {
      const value = clean(node.textContent), parent = node.parentElement;
      if (!value || !parent || parent.closest('script,style,noscript,template')) continue;
      if (!deepVisible(parent)) continue;
      range.selectNodeContents(node);
      const r = range.getBoundingClientRect();
      if (r.width > 0 && r.height > 0 && r.bottom > 0 && r.top < innerHeight && r.right > 0 && r.left < innerWidth) {
        words.push(value); length += value.length;
      }
    }
    return words.join('\n').slice(0, max);
  };

  const overlays = () => [...document.querySelectorAll('dialog[open],[role="dialog"],[role="alertdialog"],[aria-modal="true"]')]
    .filter(e => deepVisible(e))
    .slice(0, 3)
    .map(e => ({
      role: e.getAttribute('role') || 'dialog',
      name: clean(nameOf(e)).slice(0, 80),
      modal: e.getAttribute('aria-modal') === 'true' || e.tagName === 'DIALOG',
    }));

  /* ------------------------------------------------------------ readState */

  const readState = opts => {
    opts = opts || {};
    S.modalAt = -1e9;   // aa5: every snapshot re-checks which modal is on top (a click may have just opened one)
    const maxActions = opts.maxActions || 250;
    const maxText = opts.maxText || 6000;
    prune();
    const { roots, cross } = rootList();
    const height = document.documentElement.scrollHeight;

    const items = [];
    const seen = new Set();
    for (const { doc, chain } of roots) {
      for (const root of rootsOf(doc)) {
        let found = [];
        try { found = root.querySelectorAll(SELECTOR); } catch (_) { continue; }
        for (const e of found) {
          if (seen.has(e)) continue;
          if (UNSAFE_TYPES.includes(typeOf(e))) continue;
          if (!e.isConnected || !deepVisible(e) || disabled(e)) continue;
          const role = roleOf(e);
          if (!role) continue;
          if (role === 'gridcell' && e.querySelector('button,[role="button"]')) continue;
          const r = e.getBoundingClientRect();
          if (!r.width || !r.height) continue;
          seen.add(e);
          items.push({ e, role, chain, r });
        }
        if (items.length > maxActions * 6) break;
      }
    }

    const count = new Map();
    const built = [];
    let offscreen = 0;
    for (const it of items) {
      const e = it.e;
      // P2: no 160-char cut on name/label/value — the owned driver reports them whole (a 4000-char sanity
      // bound only). reinspect() below must use the same bound so the identity check stays consistent.
      const name = clean(nameOf(e)).slice(0, 4000);
      const key = it.role + '\u0000' + name.toLowerCase();
      count.set(key, (count.get(key) || 0) + 1);
      const node = identity(e);
      const r = it.r;

      const offset = it.chain.length ? frameOffset(it.chain) : { x: 0, y: 0 };
      const cx = r.x + r.width / 2 + (offset ? offset.x : 0);
      const cy = r.y + r.height / 2 + (offset ? offset.y : 0);
      const inViewport = !!offset && cx >= 0 && cy >= 0 && cx < innerWidth && cy < innerHeight;
      if (!inViewport) offscreen += 1;

      let occluded = false;
      if (inViewport) {
        try {
          const doc = e.ownerDocument, view = doc.defaultView;
          const lx = r.x + r.width / 2, ly = r.y + r.height / 2;
          if (lx < 0 || ly < 0 || lx >= view.innerWidth || ly >= view.innerHeight) occluded = true;
          else {
            const hit = deepElementFromPoint(doc, lx, ly);
            occluded = !(hit && (hit === e || e.contains(hit) || hit.contains(e)));
          }
        } catch (_) { occluded = false; }
      }

      const options = [];
      if (e.tagName === 'SELECT') {
        for (const o of e.options) {
          if (o.disabled || o.closest('optgroup[disabled]')) continue;
          options.push({
            ref: 'e' + node + ':' + (options.length + 1),
            label: clean(o.label).slice(0, 60), value: o.value, selected: !!o.selected,
          });
        }
      }
      // Login forms are a blind spot for observers that drop password fields.
      // Keep the control usable, but never let its value leave the page.
      const secretField = typeOf(e) === 'password' || (SECRET_HINT.test(name) && isEditable(e));
      const editable = isEditable(e);
      // P2 new fields for guard v2 and the fill loop.
      const formEl = e.form || (e.closest ? e.closest('form') : null);
      const dlg = e.closest ? e.closest('dialog,[role="dialog"],[role="alertdialog"]') : null;
      const consentEl = e.closest ? e.closest(CONSENT_SELECTOR) : null;
      const maxLen = (typeof e.maxLength === 'number' && e.maxLength >= 0) ? e.maxLength : null;
      const formId = formEl ? (formEl.id || formEl.getAttribute('name') || '<form>') : '';
      const dialogId = dlg ? (dlg.id || '<dialog>') : '';
      built.push({
        node, ref: 'e' + node, role: it.role, name, label: name || it.role,
        value: secretField ? '' : valueOf(e).slice(0, 4000),
        // P2: raw tag + type attribute drive guard.py's structural-submit test; the rest feed the fill loop.
        tag: e.tagName, type: typeOf(e),
        required: !!e.required || e.getAttribute('aria-required') === 'true' || /\brequired\b|\*/.test(name),
        maxlength: maxLen, placeholder: e.getAttribute('placeholder') || '',
        form: formId, dialog: dialogId,
        consent: consentEl ? (consentEl.id ? '#' + consentEl.id : '.' + (consentEl.className || '').trim().split(/\s+/)[0]) : '',
        // plan's `scope`: the nearest role=dialog / <dialog> / <form>, dialog first.
        scope: dialogId || formId,
        // P3: radio/checkbox group key for question extraction.
        // Native inputs: the HTML name attribute (the browser's radio-group key).
        // ARIA radios: the accessible name of the nearest radiogroup or fieldset.
        group: (['radio', 'checkbox'].includes(typeOf(e)) && e.tagName === 'INPUT' && e.name) ? e.name
          : (['radio', 'checkbox'].includes(it.role) && e.closest
             && e.closest('[role="radiogroup"],fieldset'))
            ? nameOf(e.closest('[role="radiogroup"],fieldset'), new Set()) : '',
        editable, occluded, inViewport,
        rank: (inViewport ? 100 : 0) + (editable || PRIMARY.has(it.role) ? 40 : 0)
          + (SECONDARY.has(it.role) ? 15 : 0),
        order: built.length,
        // aa6: ARIA radios / checkboxes / switches (LinkedIn Easy Apply's resume cards and Yes/No questions are
        // DIV role=radio with aria-checked, live 2026-09-23) report their state too.
        checked: ['checkbox', 'radio'].includes(typeOf(e)) ? !!e.checked
          : (['radio', 'checkbox', 'switch', 'menuitemradio', 'menuitemcheckbox'].includes(it.role)
             && e.hasAttribute('aria-checked')) ? e.getAttribute('aria-checked') === 'true' : null,
        expanded: e.getAttribute('aria-expanded'),
        current: e.tagName === 'SELECT' ? clean([...e.selectedOptions].map(o => o.label).join(', ')).slice(0, 120) : null,
        multiple: e.tagName === 'SELECT' ? !!e.multiple : false,
        accept: isFile(e) ? (e.getAttribute('accept') || '') : null,
        options: options.slice(0, 40),
        opts_total: options.length,
        secret: secretField,
        _ctx: clean(scopeOf(e) ? scopeOf(e).innerText : '').slice(0, 120),
      });
    }

    // Context only where a label repeats — shipping it unconditionally is waste.
    for (const b of built) {
      const key = b.role + '\u0000' + b.name.toLowerCase();
      if ((count.get(key) || 0) > 1) b.context = b._ctx;
      delete b._ctx;
    }

    // Truncate by usefulness, then restore document order for readability, so
    // hitting the cap never drops the form in favour of forty footer links.
    let kept = built;
    let omitted = 0;
    if (built.length > maxActions) {
      kept = [...built].sort((a, b) => (b.rank - a.rank) || (a.order - b.order)).slice(0, maxActions);
      kept.sort((a, b) => a.order - b.order);
      omitted = built.length - kept.length;
    }
    for (const b of kept) delete b.rank;

    const identities = {};
    for (const b of built) identities[b.node] = [b.role, b.name];
    S.snap = { key: keyOf(), guards: {}, identities };

    const actions = kept.map((b, i) => { b.index = i + 1; return b; });
    for (const b of actions) if (!(b.node in S.snap.guards)) S.snap.guards[b.node] = guardOf(S.nodes.get(b.node));

    const digest = built.map(b => [b.role, b.name, b.value, b.checked, b.current,
      b.expanded, b.occluded, b.editable].join('|')).join('\u0001');
    const text = opts.includeText === false ? '' : textOf(maxText);
    return JSON.stringify({
      url: location.href, title: document.title, w: innerWidth, h: innerHeight, text,
      scroll: { y: Math.round(scrollY), height },
      // `reachable` is the number an agent actually cares about: how many of
      // these refs can be acted on without first dismissing something.
      reachable: actions.filter(b => b.inViewport && !b.occluded).length,
      actions, omitted, offscreen,
      overlays: overlays(),
      cross_frames: cross.length,
      cross_frame_srcs: cross.slice(0, 3).map(c => c.src).filter(Boolean),
      digest, page_key: S.snap.key,
    });
  };

  /* ----------------------------------------------------- guard + geometry */

  const nodeFor = ref => S.nodes.get(
    typeof ref === 'number' ? ref : parseInt(String(ref).replace(/^e/, ''), 10));

  const refId = ref => String(String(ref).replace(/^e/, '').split(':')[0]);

  const verify = (ref, pageKey) => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    if (pageKey && keyOf() !== pageKey) return { ok: false, reason: 'page_changed' };
    const before = S.snap && S.snap.guards[refId(ref)];
    const now = guardOf(e);
    if (before == null || now !== before) return { ok: false, reason: 'target_changed' };
    return { ok: true };
  };

  // Used for the 2nd..nth op of a batch. Earlier ops in the same batch are
  // allowed to have changed values and checked state; what must still hold is
  // that this ref is the same control the agent chose.
  const reinspect = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    if (disabled(e)) return { ok: false, reason: 'disabled' };
    if (!deepVisible(e)) return { ok: false, reason: 'hidden' };
    const known = S.snap && S.snap.identities[refId(ref)];
    if (!known) return { ok: false, reason: 'unknown_ref' };
    if (known[0] !== roleOf(e) || known[1] !== clean(nameOf(e)).slice(0, 4000)) {
      return { ok: false, reason: 'target_changed' };
    }
    return { ok: true };
  };

  const resolve = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    if (disabled(e)) return { ok: false, reason: 'disabled' };
    if (!deepVisible(e)) return { ok: false, reason: 'hidden' };
    const doc = e.ownerDocument, view = doc.defaultView;
    const r = e.getBoundingClientRect();
    if (!r.width || !r.height) return { ok: false, reason: 'no_geometry' };
    const lx = r.x + r.width / 2, ly = r.y + r.height / 2;
    if (lx < 0 || ly < 0 || lx >= view.innerWidth || ly >= view.innerHeight) {
      return { ok: false, reason: 'out_of_viewport' };
    }
    const hit = deepElementFromPoint(doc, lx, ly);
    if (!hit || !(hit === e || e.contains(hit) || hit.contains(e))) {
      return { ok: false, reason: 'occluded' };
    }
    const off = offsetFor(frameChainOf(e));
    if (!off.ok) return { ok: false, reason: off.reason };
    return { ok: true, x: Math.round(lx + off.x), y: Math.round(ly + off.y) };
  };

  const scrollTo = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    try {
      e.scrollIntoView({ block: 'center', inline: 'center' });
      // scrollIntoView does not reliably cross frame boundaries, so bring every
      // containing frame into view too.
      for (const f of frameChainOf(e)) {
        try { f.scrollIntoView({ block: 'center', inline: 'center' }); } catch (_) { break; }
      }
    } catch (_) {
      return { ok: false, reason: 'scroll_failed' };
    }
    return { ok: true };
  };

  const selectOption = (ref, value) => {
    const e = nodeFor(ref);
    if (!e || e.tagName !== 'SELECT') return { ok: false, reason: 'not_a_select' };
    const options = [...e.options];
    const match = options.find(o => o.value === String(value) && !o.disabled && !o.closest('optgroup[disabled]'))
      || options.find(o => clean(o.label) === clean(String(value)) && !o.disabled && !o.closest('optgroup[disabled]'))
      || options.find(o => clean(o.label).toLowerCase() === clean(String(value)).toLowerCase());
    if (!match) return { ok: false, reason: 'no_such_option' };
    if (e.multiple) {
      match.selected = true;
    } else {
      e.value = match.value;
    }
    e.dispatchEvent(new Event('input', { bubbles: true }));
    e.dispatchEvent(new Event('change', { bubbles: true }));
    return { ok: true, value: match.value, label: clean(match.label) };
  };

  const settle = kind => new Promise(resolveDone => {
    let frames = 0, stopped = false;
    const finish = () => { if (!stopped) { stopped = true; resolveDone(); } };
    setTimeout(finish, kind === 'options' ? 200 : 50);
    const step = () => {
      if (stopped) return;
      if (++frames >= 2) return finish();
      requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  });

  const label = ref => {
    const e = nodeFor(ref);
    return e && e.isConnected ? clean(nameOf(e)).slice(0, 120) : '';
  };

  // P2: the guard-relevant descriptor of a LIVE node, read immediately before a click. The driver's
  // never-submit check (defence in depth) uses this rather than a stale observation.
  const descriptor = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return null;
    const formEl = e.form || (e.closest ? e.closest('form') : null);
    const dlg = e.closest ? e.closest('dialog,[role="dialog"],[role="alertdialog"]') : null;
    const consentEl = e.closest ? e.closest(CONSENT_SELECTOR) : null;
    return {
      ref: String(ref), role: roleOf(e) || '', tag: e.tagName, type: typeOf(e),
      name: clean(nameOf(e)).slice(0, 4000), value: valueOf(e).slice(0, 4000),
      form: formEl ? (formEl.id || formEl.getAttribute('name') || '<form>') : '',
      dialog: dlg ? (dlg.id || '<dialog>') : '',
      consent: consentEl ? (consentEl.id ? '#' + consentEl.id : '.' + (consentEl.className || '').trim().split(/\s+/)[0]) : '',
    };
  };

  const stats = () => ({ refs: S.nodes.size, next: S.next, hasSnap: !!S.snap });

  W.__jevMcp = {
    version: 15, readState, verify, reinspect, resolve, scrollTo, selectOption,
    settle, label, descriptor, stats, keyOf, guardOf,
  };
})();
